name: scheduled

on:
  schedule:
    - cron: '0 14 24 * *'
    
jobs:
  update_package:
    runs-on: ${{ matrix.config.os }}
    
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: 'release'}
          
    env:
      GITHUB_PAT: ${{ secrets.TOKEN }}
      
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          
      - name: Cache R packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          
      - name: Install dependencies
      
        if: steps.cache.outputs.cache-hit != 'true'
      
        run: |
          install.packages('remotes')
          install.packages('stringr')
          install.packages('readr')
          install.packages('here')
          install.packages("tibble")
          install.packages('lubridate')
          install.packages('EML')
          remotes::install_github('EDIorg/EDIutils', update=FALSE, ask=FALSE)
        shell: Rscript {0}
          
      - name: Publish data to EDI
        env:
            EDI_ENV: "staging"
            EDI_USER: ${{secrets.EDI_USERNAME}}
            EDI_PASS: ${{secrets.EDI_PASSWORD}}
        run: |
          source("R/EDI_update.R")
        shell: Rscript {0}